// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmrgLYoaSjNMEeOYCaZAGcDmhrx_hUrOE',
    appId: '1:724458690025:web:f0911ecb08ca0bb6316778',
    messagingSenderId: '724458690025',
    projectId: 'arm-chats',
    authDomain: 'arm-chats.firebaseapp.com',
    storageBucket: 'arm-chats.appspot.com',
    measurementId: 'G-NDW1H32HE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB4SpSsXGiSLjkgGnPM1for1A-aOg6IBg',
    appId: '1:724458690025:android:69a11733493766e4316778',
    messagingSenderId: '724458690025',
    projectId: 'arm-chats',
    storageBucket: 'arm-chats.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnETKLK0XE4TvJf1-l1xiADUSo3RmfW0A',
    appId: '1:724458690025:ios:0e42ebca1ef5da5c316778',
    messagingSenderId: '724458690025',
    projectId: 'arm-chats',
    storageBucket: 'arm-chats.appspot.com',
    iosClientId: '724458690025-dtimmvj1748hv1huot5ojklg1nvqidge.apps.googleusercontent.com',
    iosBundleId: 'com.example.armChats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnETKLK0XE4TvJf1-l1xiADUSo3RmfW0A',
    appId: '1:724458690025:ios:0e42ebca1ef5da5c316778',
    messagingSenderId: '724458690025',
    projectId: 'arm-chats',
    storageBucket: 'arm-chats.appspot.com',
    iosClientId: '724458690025-dtimmvj1748hv1huot5ojklg1nvqidge.apps.googleusercontent.com',
    iosBundleId: 'com.example.armChats',
  );
}
